### ISSUE TITLE
practica textbox personalizado

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-salathiel1999#2]
[Reporte txt personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-salathiel1999/files/6328034/Reporte.txt.personalizado.pdf)

**Comment by Yabin-2021** [comment]
[Evaluación - TextBox personalizado - Irvin Salathiel.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-salathiel1999/files/6362797/Evaluacion.-.TextBox.personalizado.-.Irvin.Salathiel.pdf)

**Anexo Evaluación del textbox personalizado:**
Calificación:
18.4%

Por Yabin España Aparicio.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
